package qoder

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"testing"

	"github.com/caigee-cmd/cli2api/internal/accounts"
	"github.com/caigee-cmd/cli2api/internal/providers"
)

// ---------------------------------------------------------------------------
// AES-128-CBC codec
// ---------------------------------------------------------------------------

func aesCBCEncryptForTest(t *testing.T, plaintext, key []byte) string {
	t.Helper()
	block, err := aes.NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	padded := padPKCS7ForTest(plaintext, aes.BlockSize)
	encrypted := make([]byte, len(padded))
	cipher.NewCBCEncrypter(block, key).CryptBlocks(encrypted, padded)
	return base64.StdEncoding.EncodeToString(encrypted)
}

func padPKCS7ForTest(data []byte, blockSize int) []byte {
	padding := blockSize - len(data)%blockSize
	pad := make([]byte, padding)
	for i := range pad {
		pad[i] = byte(padding)
	}
	return append(data, pad...)
}

const machineID = "qoder-machine-id-0123456789"

// TestDecodeUserBlobReferenceVector pins the CLI credential format against a
// vector generated by the reference implementation (qoder2api-hub
// qoder_sign.aes_cbc_encrypt), so a Go-side drift cannot go unnoticed.
func TestDecodeUserBlobReferenceVector(t *testing.T) {
	const blob = "tSve7mpCLUDF1tdUb2cF6opyT62cSEz/Fj1ZOnZzS/J1UG0jrnGjALxfxT/LRmPjujHgMhIgNHrXzJrRCx5JYQYv+BhhE8xA/kLZe9JBZp9QEIDC4BhXmbwrU924q2RkJLfH3AGZ4w68GjwBhLgMTSEpJIGjP1PP0flWOgsFHGg="
	want := userBlob{
		AccessToken:  "at-abc123",
		RefreshToken: "jrt-xyz789",
		UID:          "u-1",
		Name:         "tester",
		ExpireTime:   1893456000000,
	}
	cred, err := decodeUserBlob([]byte(blob), machineID)
	if err != nil {
		t.Fatal(err)
	}
	if cred.AccessToken != want.AccessToken || cred.RefreshToken != want.RefreshToken ||
		cred.UID != want.UID || cred.Name != want.Name || cred.ExpireTime != want.ExpireTime {
		t.Fatalf("decoded = %+v want %+v", cred, want)
	}
	if cred.bearerToken() != want.AccessToken {
		t.Fatalf("bearerToken = %q", cred.bearerToken())
	}
}

func TestDecodeUserBlobPlaintext(t *testing.T) {
	plain := []byte(`{"access_token":"at-p","refresh_token":"drt-r","uid":"u-2","name":"plain","expire_time":123}`)
	cred, err := decodeUserBlob(plain, "whatever-machine")
	if err != nil {
		t.Fatal(err)
	}
	if cred.AccessToken != "at-p" || cred.RefreshToken != "drt-r" || cred.UID != "u-2" {
		t.Fatalf("decoded = %+v", cred)
	}
}

func TestDecodeUserBlobRejectsBadInput(t *testing.T) {
	for _, tc := range []struct {
		name      string
		blob      string
		machineID string
	}{
		{name: "empty blob", blob: ""},
		{name: "empty machine on encrypted blob", blob: "Uvd3BzZUjVdhKjPKMWkLnw==", machineID: ""},
		{name: "short machine on encrypted blob", blob: "Uvd3BzZUjVdhKjPKMWkLnw==", machineID: "short"},
		{name: "invalid base64", blob: "not-base64!!!", machineID: "qoder-machine-id-0123456789"},
		{name: "block misaligned", blob: "dG9vbG9uZw==", machineID: "qoder-machine-id-0123456789"},
		{name: "padding corrupt", blob: "Uvd3BzZUjVdhKjPKMWkLnw==", machineID: "qoder-machine-id-0123456789"},
		{name: "not json", blob: "YWJjZGVmZ2hpamtsbW5vcA==", machineID: "qoder-machine-id-0123456789"},
		{name: "json without token", blob: `{"uid":"u-9"}`, machineID: "whatever"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := decodeUserBlob([]byte(tc.blob), tc.machineID); err == nil {
				t.Fatalf("decodeUserBlob(%q) accepted", tc.blob)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// fake store
// ---------------------------------------------------------------------------

type fakeNativeStore struct {
	mu         sync.Mutex
	account    accounts.Account
	credential accounts.NativeCredential
	proxy      string

	getErr  error
	loadErr error

	credentials     []accounts.NativeCredential
	credentialsByID []string
}

func (s *fakeNativeStore) Get(_ context.Context, _ string) (accounts.Account, error) {
	if s.getErr != nil {
		return accounts.Account{}, s.getErr
	}
	return s.account, nil
}

func (s *fakeNativeStore) LoadCredential(_ context.Context, _ string) (accounts.NativeCredential, error) {
	if s.loadErr != nil {
		return accounts.NativeCredential{}, s.loadErr
	}
	return s.credential, nil
}

func (s *fakeNativeStore) SaveCredential(_ context.Context, accountID string, _ string, credential accounts.NativeCredential) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.credentials = append(s.credentials, credential)
	s.credentialsByID = append(s.credentialsByID, accountID)
	return nil
}

func (s *fakeNativeStore) GetSecret(_ context.Context, _ string) (string, bool, error) {
	if s.proxy != "" {
		return s.proxy, true, nil
	}
	return "", false, nil
}

func newNativeClient(store *fakeNativeStore) *Client {
	client := NewClient(store)
	client.Bind(func(string) (string, bool) { return "", false }, func() string { return "" })
	return client
}

func missingClient(store *fakeNativeStore) *Client {
	return newNativeClient(store)
}

func encryptedCredential(t *testing.T, machineID string, mutate func(map[string]any)) accounts.NativeCredential {
	t.Helper()
	user := map[string]any{
		"access_token":  "at-old",
		"refresh_token": "jrt-old",
		"uid":           "u-1",
		"name":          "tester",
		"expire_time":   1893456000000,
	}
	if mutate != nil {
		mutate(user)
	}
	raw, _ := json.Marshal(user)
	return accounts.NativeCredential{
		UserBlob:  []byte(aesCBCEncryptForTest(t, raw, []byte(machineID[:16]))),
		MachineID: machineID,
	}
}

func cnAccount(_ string) accounts.Account {
	return accounts.Account{ID: "acc-1", Provider: "qoder", ProviderRegion: "cn", AuthType: "qoder-native-v1"}
}

// pointCnat installs the httptest server as the cn openapi host.
func pointCnAt(t *testing.T, client *Client, upstreamURL string) {
	t.Helper()
	client.setEndpoints(map[string]nativeEndpoints{
		"cn": {base: upstreamURL, origin: upstreamURL},
	})
}

// ---------------------------------------------------------------------------
// Checkin (native)
// ---------------------------------------------------------------------------

func TestCheckinNativeClaimsCampaign(t *testing.T) {
	var sawHeaders http.Header
	var sawAuth, sawMachine string
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		sawHeaders = r.Header.Clone()
		sawAuth = strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
		sawMachine = r.Header.Get("Cosy-MachineId")
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/sash/api/v1/me/campaigns":
			_, _ = w.Write([]byte(`{"campaigns":[
				{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMED","benefit":{"kind":"CREDITS","amount":100}},
				{"campaignId":"c2","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMABLE","benefit":{"kind":"CREDITS","amount":100}},
				{"campaignId":"c3","actionType":"OTHER_ACTION","claimStatus":"CLAIMABLE","benefit":{"kind":"CREDITS","amount":500}}
			]}`))
		case r.Method == http.MethodPost && r.URL.Path == "/sash/api/v1/me/campaigns/c2/claim":
			_, _ = w.Write([]byte(`{"data":{"campaignId":"c2","status":"CLAIMED"}}`))
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer upstream.Close()

	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	result, err := client.Checkin(context.Background(), "acc-1")
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != "success" || result.RewardCredits != 100 {
		t.Fatalf("result = %+v", result)
	}
	if sawAuth != "at-old" || sawMachine != machineID {
		t.Fatalf("auth=%q machine=%q", sawAuth, sawMachine)
	}
	if sawHeaders.Get("User-Agent") != "Qoder" || sawHeaders.Get("Cosy-ClientType") != "10" ||
		sawHeaders.Get("Cosy-Version") != "0.3.4" ||
		sawHeaders.Get("Cosy-MachineToken") != machineID ||
		sawHeaders.Get("Referer") != upstream.URL+"/growth-page/activity-iframe" {
		t.Fatalf("headers = %v", sawHeaders)
	}
}

func TestCheckinNativeAlreadyAndSkipped(t *testing.T) {
	for _, tc := range []struct {
		name     string
		listBody string
		want     string
	}{
		{name: "claimed only", listBody: `{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMED","benefit":{"kind":"CREDITS","amount":100}}]}`, want: "already"},
		{name: "no credit kind", listBody: `{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMABLE","benefit":{"kind":"DISCOUNT","amount":1}}]}`, want: "skipped"},
		{name: "nothing claimable", listBody: `{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"MISSED","benefit":{"kind":"CREDITS","amount":100}}]}`, want: "skipped"},
		{name: "empty campaigns", listBody: `{"campaigns":[]}`, want: "skipped"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				_, _ = w.Write([]byte(tc.listBody))
			}))
			defer upstream.Close()
			store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
			client := newNativeClient(store)
			client.SetHTTP(upstream.Client())
			pointCnAt(t, client, upstream.URL)
			result, err := client.Checkin(context.Background(), "acc-1")
			if err != nil || result.Status != tc.want {
				t.Fatalf("result=%+v err=%v", result, err)
			}
		})
	}
}

func TestCheckinNativeRecoversUnconfirmedClaim(t *testing.T) {
	var claimed atomic.Bool
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/sash/api/v1/me/campaigns":
			status := "CLAIMABLE"
			if claimed.Load() {
				status = "CLAIMED"
			}
			_, _ = w.Write([]byte(`{"data":{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"` + status + `","benefit":{"kind":"CREDITS","amount":100}}]}}`))
		case r.Method == http.MethodPost && r.URL.Path == "/sash/api/v1/me/campaigns/c1/claim":
			// Upstream accepted the claim but answered without a status; the
			// follow-up list observes CLAIMED.
			claimed.Store(true)
			_, _ = w.Write([]byte(`{"data":{"campaignId":"c1"}}`))
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer upstream.Close()

	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	result, err := client.Checkin(context.Background(), "acc-1")
	if err != nil {
		t.Fatal(err)
	}
	// No claim round confirmed CLAIMED directly, but the re-list proved the
	// benefit landed: the already-style recovery path.
	if result.Status != "already" {
		t.Fatalf("result = %+v", result)
	}
}

func TestCheckinNativeDataArrayShape(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"data":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMED","benefit":{"kind":"CREDITS","amount":50}}]}`))
	}))
	defer upstream.Close()

	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	result, err := client.Checkin(context.Background(), "acc-1")
	if err != nil || result.Status != "already" {
		t.Fatalf("result=%+v err=%v", result, err)
	}
}

func TestCheckinNativeClaimUnconfirmedFails(t *testing.T) {
	var claimPosts int
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodGet && r.URL.Path == "/sash/api/v1/me/campaigns":
			_, _ = w.Write([]byte(`{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMABLE","benefit":{"kind":"CREDITS","amount":100}}]}`))
		case r.Method == http.MethodPost && r.URL.Path == "/sash/api/v1/me/campaigns/c1/claim":
			claimPosts++
			_, _ = w.Write([]byte(`{"data":{"status":"PENDING"}}`))
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer upstream.Close()

	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	if _, err := client.Checkin(context.Background(), "acc-1"); err == nil {
		t.Fatal("unconfirmed claim must fail")
	}
	if claimPosts != 1 {
		t.Fatalf("claim posts = %d, no silent retry", claimPosts)
	}
}

func TestCheckinNative404Skips(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusNotFound)
	}))
	defer upstream.Close()
	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)
	result, err := client.Checkin(context.Background(), "acc-1")
	if err != nil || result.Status != "skipped" {
		t.Fatalf("result=%+v err=%v", result, err)
	}
}

func TestCheckinNative401RefreshesAndRetries(t *testing.T) {
	var listCalls, refreshCalls int
	var secondListAuth string
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodPost && r.URL.Path == "/api/v1/jobToken/refresh":
			refreshCalls++
			body, _ := io.ReadAll(r.Body)
			if string(body) != `{"refresh_token":"jrt-old"}` {
				t.Errorf("refresh body = %s", body)
			}
			_, _ = w.Write([]byte(`{"token":"at-new","refresh_token":"jrt-new","expires_in":3600000}`))
		case r.Method == http.MethodGet && r.URL.Path == "/sash/api/v1/me/campaigns":
			listCalls++
			if listCalls == 1 {
				w.WriteHeader(http.StatusUnauthorized)
				return
			}
			secondListAuth = strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
			_, _ = w.Write([]byte(`{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMED","benefit":{"kind":"CREDITS","amount":100}}]}`))
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer upstream.Close()

	cred := encryptedCredential(t, machineID, nil)
	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: cred}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	result, err := client.Checkin(context.Background(), "acc-1")
	if err != nil || result.Status != "already" {
		t.Fatalf("result=%+v err=%v", result, err)
	}
	if refreshCalls != 1 || listCalls != 2 {
		t.Fatalf("refreshCalls=%d listCalls=%d", refreshCalls, listCalls)
	}
	if secondListAuth != "at-new" {
		t.Fatalf("retry auth = %q", secondListAuth)
	}
	// The refreshed blob must be persisted with tokens patched in.
	if len(store.credentials) != 1 {
		t.Fatalf("SaveCredential calls = %d", len(store.credentials))
	}
	saved, err := decodeUserBlob(store.credentials[0].UserBlob, machineID)
	if err != nil {
		t.Fatal(err)
	}
	if saved.AccessToken != "at-new" || saved.RefreshToken != "jrt-new" || saved.ExpireTime == 1893456000000 {
		t.Fatalf("saved credential = %+v", saved)
	}
	if !isEncryptedBlob(store.credentials[0].UserBlob) {
		t.Fatal("encrypted blob must stay encrypted after write-back")
	}
	if store.credentialsByID[0] != "acc-1" {
		t.Fatalf("saved under %q", store.credentialsByID[0])
	}
}

func TestCheckinNativeRefreshFailsReReadsStore(t *testing.T) {
	var listCalls int
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodPost && r.URL.Path == "/api/v1/jobToken/refresh":
			w.WriteHeader(http.StatusBadRequest)
			_, _ = w.Write([]byte(`{"message":"bad"}`))
		case r.Method == http.MethodGet && r.URL.Path == "/sash/api/v1/me/campaigns":
			listCalls++
			if listCalls == 1 {
				w.WriteHeader(http.StatusUnauthorized)
				return
			}
			// After re-reading the rotated credential from the store the new
			// token must be used for the retry.
			if got := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer "); got != "at-rotated" {
				t.Errorf("retry auth = %q", got)
			}
			_, _ = w.Write([]byte(`{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMED","benefit":{"kind":"CREDITS","amount":100}}]}`))
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer upstream.Close()

	store := &fakeNativeStore{account: cnAccount(upstream.URL)}
	store.credential = accounts.NativeCredential{
		UserBlob:  []byte(`{"access_token":"at-rotated","refresh_token":"jrt-rotated","uid":"u-1"}`),
		MachineID: machineID,
	}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	result, err := client.Checkin(context.Background(), "acc-1")
	if err != nil || result.Status != "already" {
		t.Fatalf("result=%+v err=%v", result, err)
	}
	if listCalls != 2 {
		t.Fatalf("listCalls = %d", listCalls)
	}
}

func TestCheckinNativeCredentialErrors(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusUnauthorized)
	}))
	defer upstream.Close()

	missing := &fakeNativeStore{account: cnAccount(upstream.URL), loadErr: os.ErrNotExist}
	if _, err := missingClient(missing).Checkin(context.Background(), "acc-1"); err == nil {
		t.Fatal("missing credential must fail")
	}

	unreadable := &fakeNativeStore{account: cnAccount(upstream.URL), credential: accounts.NativeCredential{MachineID: machineID}}
	if _, err := missingClient(unreadable).Checkin(context.Background(), "acc-1"); err == nil {
		t.Fatal("unreadable credential must fail")
	}
}

func TestCheckinNativeRegionAndStore(t *testing.T) {
	// No store: native check-in cannot work and must fail with a clear error.
	if _, err := NewClient(nil).Checkin(context.Background(), "acc-1"); err == nil {
		t.Fatal("expected error without native store")
	}
	// Store bound but credential missing: the worker path is gone, so this
	// must surface as an error, not a silent skip.
	missing := &fakeNativeStore{account: cnAccount("http://unused"), loadErr: os.ErrNotExist}
	if _, err := missingClient(missing).Checkin(context.Background(), "acc-1"); err == nil {
		t.Fatal("expected error for missing credential")
	}
}

func TestCheckinNativeRefreshFailureSurfacesError(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodPost && r.URL.Path == "/api/v1/jobToken/refresh":
			w.WriteHeader(http.StatusForbidden)
			_, _ = w.Write([]byte(`{"message":"TOKEN_EXPIRE"}`))
		case r.Method == http.MethodGet && r.URL.Path == "/sash/api/v1/me/campaigns":
			w.WriteHeader(http.StatusUnauthorized)
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer upstream.Close()
	cred := encryptedCredential(t, machineID, func(user map[string]any) {
		user["refresh_token"] = "jrt-dead"
	})
	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: cred}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)
	if _, err := client.Checkin(context.Background(), "acc-1"); err == nil {
		t.Fatal("session-dead refresh failure must surface")
	}
}

// ---------------------------------------------------------------------------
// Quota (native)
// ---------------------------------------------------------------------------

func TestNativeQuotaDecodesUpstream(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet || r.URL.Path != "/api/v2/quota/usage" {
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
			return
		}
		_, _ = w.Write([]byte(`{
			"isQuotaExceeded": true,
			"totalUsagePercentage": 100,
			"userQuota": {"total": 100, "used": 100, "remaining": 0, "percentage": 100, "unit": "credits"},
			"addOnQuota": {"total": 50, "used": 10, "remaining": 40, "unit": "credits"}
		}`))
	}))
	defer upstream.Close()

	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	snapshot, err := client.QuotaSnapshot(context.Background(), "acc-1", true)
	if err != nil {
		t.Fatal(err)
	}
	if snapshot == nil || !snapshot.HasAddOn || snapshot.AddOnRemaining != 40 {
		t.Fatalf("snapshot = %+v", snapshot)
	}
	if snapshot.Exceeded {
		t.Fatal("add-on remaining must keep Exceeded false")
	}

	info, err := client.Quota(context.Background(), "acc-1")
	if err != nil || info == nil || info.Remaining != 40 || info.Total != 150 {
		t.Fatalf("info = %+v err=%v", info, err)
	}
}

func TestNativeQuotaFallsBackToWorkerWithoutStore(t *testing.T) {
	var quotaHits int
	worker := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/admin/quota" {
			t.Errorf("path = %s", r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
			return
		}
		quotaHits++
		_, _ = w.Write([]byte(`{"ok":true,"quota":{"isQuotaExceeded":false,"fetchedAt":"now","userQuota":{"total":30,"used":12,"remaining":18,"percentage":40,"unit":"credits"}}}`))
	}))
	defer worker.Close()

	// No native store: the structural fallback reaches the worker hot path.
	client := NewClient(nil)
	client.SetHTTP(worker.Client())
	client.Bind(func(string) (string, bool) { return worker.URL, true }, func() string { return "local-key" })

	snapshot, err := client.QuotaSnapshot(context.Background(), "acc-1", true)
	if err != nil {
		t.Fatal(err)
	}
	if quotaHits != 1 {
		t.Fatalf("worker quota hits = %d", quotaHits)
	}
	if snapshot == nil || snapshot.Remaining != 18 {
		t.Fatalf("snapshot = %+v", snapshot)
	}
}

func TestNativeQuotaFallsBackToWorkerWhenDecodeFails(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/api/v2/quota/usage":
			_, _ = w.Write([]byte(`{"userQuota": 17}`))
		case "/admin/quota":
			_, _ = w.Write([]byte(`{"ok":true,"quota":{"isQuotaExceeded":false,"fetchedAt":"now","userQuota":{"total":30,"used":12,"remaining":18,"percentage":40,"unit":"credits"}}}`))
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer upstream.Close()

	// Credential decodes fine but upstream answers with an undecodable shape.
	// A shape mismatch means the worker (which calls the same upstream through
	// its own client) would hit it too, but this stays the fallback seam for
	// an older worker cache format: the decode error is classified as a
	// native-attempt failure and surfaces unless the worker succeeds.
	store := &fakeNativeStore{account: cnAccount(upstream.URL), credential: encryptedCredential(t, machineID, nil)}
	client := NewClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)
	client.Bind(func(string) (string, bool) { return upstream.URL, true }, func() string { return "local-key" })

	_, err := client.QuotaSnapshot(context.Background(), "acc-1", true)
	if err == nil {
		t.Fatal("transient native decode failure must surface, not fall back")
	}
	if !strings.Contains(err.Error(), "decode quota usage") {
		t.Fatalf("err = %v", err)
	}
}

// ---------------------------------------------------------------------------
// Adapter bundle / disabled-account checkin
// ---------------------------------------------------------------------------

func TestQoderAdapterRegistersProber(t *testing.T) {
	store := &fakeNativeStore{account: cnAccount("http://unused"), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	adapter := client.Adapter()
	if adapter.Prober == nil {
		t.Fatal("Prober must be registered once quota/probe are native")
	}
	if adapter.Checkin == nil {
		t.Fatal("Checkin must stay registered")
	}
}

func TestDisabledAccountNativeCheckinSkipsWorker(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet && r.URL.Path == "/sash/api/v1/me/campaigns" {
			_, _ = w.Write([]byte(`{"campaigns":[{"campaignId":"c1","actionType":"CLAIM_BENEFIT","claimStatus":"CLAIMED","benefit":{"kind":"CREDITS","amount":100}}]}`))
			return
		}
		t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
		w.WriteHeader(http.StatusNotFound)
	}))
	defer upstream.Close()

	cred := encryptedCredential(t, machineID, nil)
	disabled := cnAccount(upstream.URL)
	disabled.Enabled = false
	store := &fakeNativeStore{account: disabled, credential: cred}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)
	// locate is bound (as in production) but the disabled account has no pool
	// entry, so the worker lookup misses and the native path must not care.
	result, err := client.Checkin(context.Background(), "acc-1")
	if err != nil || result.Status != "already" {
		t.Fatalf("result=%+v err=%v", result, err)
	}
}

func TestProbeRunsWorkerHealthWhenRunning(t *testing.T) {
	health := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/health" {
			t.Errorf("path = %s", r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
			return
		}
		_, _ = w.Write([]byte(`{"ok":true,"ready":true,"hot":true,"uid":"u-1"}`))
	}))
	defer health.Close()

	store := &fakeNativeStore{account: cnAccount("http://unused"), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(health.Client())
	client.Bind(func(string) (string, bool) { return health.URL, true }, func() string { return "" })

	got, err := client.Probe(context.Background(), "acc-1")
	if err != nil {
		t.Fatal(err)
	}
	if !got.Ready || !got.Hot || got.UID != "u-1" {
		t.Fatalf("health = %+v", got)
	}
}

func TestProbeRunningWorkerUnavailableTakesWorkerVerdict(t *testing.T) {
	store := &fakeNativeStore{account: cnAccount("http://unused"), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	// Bound locate returns a URL whose worker is not reachable: a running
	// worker's own verdict wins over a credential-derived guess.
	client.Bind(func(string) (string, bool) { return "http://127.0.0.1:1", true }, func() string { return "" })

	got, err := client.Probe(context.Background(), "acc-1")
	if err != nil {
		t.Fatal(err)
	}
	if got.Ready {
		t.Fatalf("worker-down item must not report ready: %+v", got)
	}
	if got.LastError == "" {
		t.Fatal("worker-down probe must carry the worker error")
	}
}

func TestProbeWithoutPoolEntryFallsBackToCredential(t *testing.T) {
	cred := encryptedCredential(t, machineID, nil)
	credOnly := cnAccount("http://unused")
	credOnly.Enabled = false
	store := &fakeNativeStore{account: credOnly, credential: cred}
	client := newNativeClient(store)
	// locate (production: manager.AccountURL) finds nothing for a stopped
	// account; the credential verdict must decide without any network call.
	client.Bind(func(string) (string, bool) { return "", false }, func() string { return "" })

	got, err := client.Probe(context.Background(), "acc-1")
	if err != nil {
		t.Fatal(err)
	}
	if !got.Ready || got.UID != "u-1" {
		t.Fatalf("health = %+v", got)
	}
	if got.LastError != "" {
		t.Fatalf("unexpected LastError: %q", got.LastError)
	}
}

func TestProbeCredentialDecodeFailureReportsLoginRequired(t *testing.T) {
	// No running worker, credential undecodable: probe must say not-ready.
	dead := accounts.Account{ID: "acc-1", Provider: "qoder", ProviderRegion: "cn"}
	store := &fakeNativeStore{account: dead, credential: accounts.NativeCredential{UserBlob: []byte("junk"), MachineID: "qoder-machine-id-0123456789"}}
	client := newNativeClient(store)

	got, err := client.Probe(context.Background(), "acc-1")
	if err != nil {
		t.Fatal(err)
	}
	if got.Ready || got.LastError == "" {
		t.Fatalf("health = %+v", got)
	}
}

func TestProbeCredentialVerdictNeedsNoNetwork(t *testing.T) {
	calls := 0
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		calls++
		w.WriteHeader(http.StatusInternalServerError)
	}))
	defer upstream.Close()

	store := &fakeNativeStore{account: cnAccount("http://unused"), credential: encryptedCredential(t, machineID, nil)}
	client := newNativeClient(store)
	client.SetHTTP(upstream.Client())
	pointCnAt(t, client, upstream.URL)

	got, err := client.Probe(context.Background(), "acc-1")
	if err != nil {
		t.Fatal(err)
	}
	if !got.Ready || got.UID != "u-1" {
		t.Fatalf("health = %+v", got)
	}
	if calls != 0 {
		t.Fatalf("credential probe must not hit upstream, calls = %d", calls)
	}
}

var _ providers.AccountCheckiner = (interface {
	Checkin(context.Context, string) (providers.CheckinResult, error)
})(nil)
