package qoder

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"
)

// Daily-check-in risk identity: the sash campaign service only surfaces the
// CLAIM_BENEFIT campaign to requests that carry the desktop risk triple
// (Cosy-MachineToken / Cosy-MachineCode / Cosy-MachineType) generated by the
// Qoder app's bundled runtime-info helper, bound to the account uid. Verified
// live 2026-10-07: the same campaigns call without the triple lists only the
// VIEW_DETAILS campaign (observed on CN; CreditDaddy/upstream worker send the
// triple for both regions).
//
// Helper invocation mirrors the upstream worker and CreditDaddy:
//
//	runtime-info-<platform>-<arch>-* <env> [--account-stdin]
//
// env is 3 for the global app and 0 for the CN app (CreditDaddy CLI_RISK_ENV);
// the helper prints one JSON line {machineToken, machineCode, machineType}.
// On darwin/windows the account uid is piped via stdin as {"account": uid}.

const (
	riskIdentityTimeout  = 15 * time.Second
	riskIdentityCacheTTL = 8 * time.Hour
)

// riskIdentityOverride lets tests replace the helper lookup; nil in production.
var riskIdentityOverride func(region, uid string) (*riskIdentity, error)

type riskIdentity struct {
	MachineToken string `json:"machineToken"`
	MachineCode  string `json:"machineCode"`
	MachineType  string `json:"machineType"`
}

func (r riskIdentity) complete() bool {
	return r.MachineToken != "" && r.MachineCode != "" && r.MachineType != ""
}

// riskIdentityHeaders projects the triple onto sash request headers. The
// MachineId/MachineToken pair stays the stored machine id (set by
// checkinHeaders); the triple overrides MachineToken and adds Code/Type.
func riskIdentityHeaders(risk *riskIdentity) map[string]string {
	if risk == nil || !risk.complete() {
		return nil
	}
	return map[string]string{
		"Cosy-MachineToken": risk.MachineToken,
		"Cosy-MachineCode":  risk.MachineCode,
		"Cosy-MachineType":  risk.MachineType,
	}
}

// riskEnv maps a provider region to the runtime-info variant argument.
func riskEnv(region string) string {
	if strings.EqualFold(strings.TrimSpace(region), "cn") {
		return "0"
	}
	return "3"
}

// riskHelperHomes lists candidate Qoder HOME directories, CN app first for the
// CN region (its helper lands in ~/.qoder-cn/.bin, the global one in
// ~/.qoder/.bin), then the other one as fallback — same order CreditDaddy uses.
func riskHelperHomes(region string) []string {
	cn := []string{
		os.Getenv("QODER_CN_HOME"),
		filepath.Join(homeDir(), ".qoder-cn"),
	}
	gl := []string{
		os.Getenv("QODER_HOME"),
		filepath.Join(homeDir(), ".qoder"),
	}
	if strings.EqualFold(strings.TrimSpace(region), "cn") {
		return append(cn, gl...)
	}
	return append(gl, cn...)
}

func homeDir() string {
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		return home
	}
	return os.Getenv("HOME")
}

// riskHelperPath picks the newest runtime-info helper across the candidate
// homes. The app drops one per platform/arch; sorting picks the latest.
func riskHelperPath(region string) string {
	prefix := fmt.Sprintf("runtime-info-%s-%s-", goPlatform(), goArch())
	for _, home := range riskHelperHomes(region) {
		if strings.TrimSpace(home) == "" {
			continue
		}
		bin := filepath.Join(home, ".bin")
		entries, err := os.ReadDir(bin)
		if err != nil {
			continue
		}
		var names []string
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasPrefix(entry.Name(), prefix) {
				names = append(names, entry.Name())
			}
		}
		if len(names) == 0 {
			continue
		}
		return filepath.Join(bin, names[len(names)-1])
	}
	return ""
}

func goPlatform() string {
	switch runtime.GOOS {
	case "windows":
		return "win32"
	case "darwin":
		return "darwin"
	default:
		return runtime.GOOS
	}
}

func goArch() string {
	switch runtime.GOARCH {
	case "arm64":
		return "arm64"
	case "amd64":
		return "x64"
	default:
		return runtime.GOARCH
	}
}

// runRiskIdentity executes the helper and parses the first JSON output line.
func runRiskIdentity(ctx context.Context, helperPath, env, uid string) (*riskIdentity, error) {
	runCtx, cancel := context.WithTimeout(ctx, riskIdentityTimeout)
	defer cancel()
	args := []string{env}
	stdinPayload := ""
	switch runtime.GOOS {
	case "darwin", "windows":
		args = append(args, "--account-stdin")
		stdinPayload = fmt.Sprintf("{\"account\":%q}\n", uid)
	}
	cmd := exec.CommandContext(runCtx, helperPath, args...)
	if stdinPayload != "" {
		cmd.Stdin = strings.NewReader(stdinPayload)
	}
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("runtime-info: %w", err)
	}
	line := output
	if index := indexByte(output, '\n'); index >= 0 {
		line = output[:index]
	}
	var identity riskIdentity
	if err := json.Unmarshal(line, &identity); err != nil {
		return nil, fmt.Errorf("runtime-info output: %w", err)
	}
	if !identity.complete() {
		return nil, errors.New("runtime-info returned an incomplete identity")
	}
	return &identity, nil
}

func indexByte(b []byte, c byte) int {
	for i := range b {
		if b[i] == c {
			return i
		}
	}
	return -1
}

// riskIdentityCache memoizes identities per region:uid; the helper costs a
// process spawn and its output is stable per device, so cache aggressively.
type riskIdentityCache struct {
	mu       sync.Mutex
	entries  map[string]riskCacheEntry
	nowFunc  func() time.Time
	lookup   func(region, uid string) (*riskIdentity, error)
	override func(region, uid string) (*riskIdentity, error)
}

type riskCacheEntry struct {
	identity riskIdentity
	fetched  time.Time
}

func newRiskIdentityCache() *riskIdentityCache {
	return &riskIdentityCache{
		entries: map[string]riskCacheEntry{},
		nowFunc: time.Now,
	}
}

func (c *riskIdentityCache) get(region, uid string) (*riskIdentity, error) {
	if c.override != nil {
		return c.override(region, uid)
	}
	key := strings.ToLower(strings.TrimSpace(region)) + ":" + strings.TrimSpace(uid)
	c.mu.Lock()
	entry, ok := c.entries[key]
	c.mu.Unlock()
	if ok && c.nowFunc().Sub(entry.fetched) < riskIdentityCacheTTL {
		identity := entry.identity
		return &identity, nil
	}
	lookup := c.lookup
	if lookup == nil {
		lookup = defaultRiskLookup
	}
	identity, err := lookup(region, uid)
	if err != nil {
		return nil, err
	}
	c.mu.Lock()
	c.entries[key] = riskCacheEntry{identity: *identity, fetched: c.nowFunc()}
	c.mu.Unlock()
	return identity, nil
}

func defaultRiskLookup(region, uid string) (*riskIdentity, error) {
	if strings.TrimSpace(uid) == "" {
		return nil, errors.New("no account uid for risk identity")
	}
	helperPath := riskHelperPath(region)
	if helperPath == "" {
		return nil, errors.New("no runtime-info helper installed")
	}
	return runRiskIdentity(context.Background(), helperPath, riskEnv(region), uid)
}
